server:
  port: 8090
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  thymeleaf:
    prefix: classpath:/view/
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: account
    password: account
  jpa:
    show-sql: true

service:
  exchange:
    token:
      44b48c61421c07b0c9adfb9deddbde21
    url:
      all-exchange: http://data.fixer.io/api/latest?access_key=%s

logging:
  level:
    org.springframework: error
  file:
    path: log
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
  logback:
    rollingpolicy:
      clean-history-on-start: false
