server:
  port: 8090
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  thymeleaf:
    prefix: classpath:/view/
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: account
    password: account
  jpa:
    show-sql: true
